apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob.yaml
  - namespace.yaml
  - pvc.yaml
  - secrets.sops.yaml
configMapGenerator:
  - name: renovate-config
    namespace: renovate
    files:
      - data/renovate.json
