apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache-pvc
  namespace: renovate
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs-rwx
  resources:
    requests:
      storage: 5Gi
