apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  ports:
    - name: http
      port: 18123
      protocol: TCP
      targetPort: 8123
  clusterIP: None
  type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    kubernetes.io/service-name: homeassistant
addressType: IPv4
endpoints:
  - addresses:
      - ${MGMT_PREFIX}.52
ports:
  - name: http
    port: 8123
    protocol: TCP
