apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrolebinding.yaml
  - configmap.yaml
  - deployment.yaml
  - dnsendpoint.yaml
  - httproute.yaml
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: homepage-images
    namespace: homepage
    options:
      disableNameSuffixHash: true
    files:
      - background.webp=data/background.webp
