apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - cronjob.yaml
  - deployment.yaml
  - httproute.yaml
  - rbac.yaml
  - service.yaml
  - secrets.sops.yaml
  - google-credentials.sops.yaml
  - github-app.sops.yaml
