apiVersion: v1
kind: Secret
metadata:
    name: withjoy-exporter-env
    namespace: withjoy-exporter
type: Opaque
stringData:
    WITHJOY_USERNAME: ENC[AES256_GCM,data:S344zzmA1TpmjPgE/hKW24h/jCQiVMFfozcANfPftRj3i8V7k9vHRB4=,iv:tJLw9G+ZFoK8v15CCNBKKYdlh7okDZcCkkuECQ80Nes=,tag:ryWPeY7/47vK2ZYR817ZLg==,type:str]
    WITHJOY_PASSWORD: ENC[AES256_GCM,data:d4wq/qNES86b/TxzEb4GmRaImp8=,iv:wK9IgirvZpFx83YpOJ6fiG0tCfP8gtxHt6S7rKubTmI=,tag:5SzFM4H2zl5SWhuImaFyuA==,type:str]
    WITHJOY_GUEST_LIST_URL: ENC[AES256_GCM,data:tKHA2wYW8Imarck+bVqkNUbTbcACju6tAr5fSJ5JJBg14BRV4QLjEtoATJva6W5X16xl,iv:YvZEyf7s6PnmbMd4y5T/Yeo0M2QA7ytxPg8sGterCFg=,tag:z9bOnuq+Opm42hPhEdwMkQ==,type:str]
    SHEET_ID: ENC[AES256_GCM,data:vzh9FUy9Dt9j/iFj/lJD1aNictjb15cMCZswxXuQNDMiF8z7KtJPdG/idts=,iv:Z+zz7E/SAiFW2fyOaLyF9guiTQ0HNp91aDrLU0Fsf9w=,tag:LEAZmMomo5NhxvP76oTXww==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbUY2K0pGTkw0RG51eC9L
            aWJHb3EwMVVzK1ZHcUtQenQyY09mM21RZFZvCmVxRjRTTUMrbVpDUzdjdFdrb2U0
            NHBvc0hQZnZrSlFDdzVVcjErNWYyUEkKLS0tIHJVWmlsWGVmSSt6cFFyaDU1WCth
            dWsxbXJ0Y3NXZzQ3aER6M2ljRmM3OUUKNNPQ0+g53wig7kDcLybeI7saSXnLW/6X
            mOl5ZboShczCPDH6IYKQRgoqAeayS78QfkrLc8K9U8U43bi4qBV/GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T15:59:32Z"
    mac: ENC[AES256_GCM,data:iQ9xNkt7y+HDdBRWIrZedxh3QrN0o+nUCbFpUXkBuLrc79KHDoxobjjvvLLQxsJstlWuAilgQXIYbdckrtX2GGq5rs7+/7QDm2ecyp0VQQnPBA/RhDlZHk3kk6OccNmtXqk7tjO7J5xLfIVFaAr0qxg8x0sILYQyLSavFkc9mCE=,iv:WPnrZsy0w7ggSWw0m9aOykfE4i2J6iHlQhRiE6CgSyE=,tag:S9ljB8QB8MVEw4YZ8AyFkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
