apiVersion: v1
kind: Service
metadata:
  name: mkdocs
  namespace: mkdocs
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "mkdocs"
spec:
  type: LoadBalancer
  selector:
    app: mkdocs
  ports:
    - port: 6080
      targetPort: 80
      protocol: TCP
      name: mkdocs-http
