apiVersion: ENC[AES256_GCM,data:NQ4=,iv:bFY59cDBsU4dXFJPWZ4lK848jtbRGz2Uzi9JFSnP04Q=,tag:1qtmGD14wzTbM1w1T+jThQ==,type:str]
kind: ENC[AES256_GCM,data:TRpbTv+e,iv:6eOQy+UyrOVy20ok/iclNtoUxPLUFpv0MQrDDS8Dw6M=,tag:hrqvNWSTfm2GUQkss/HCNQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3G8UmokyE89XDHjULw==,iv:TuYcdFI8JhRPPO2IuhoegK42AQJsy0w6RYtEPo0EGdM=,tag:VLB5U8PAXM1vFyUzg5ejfw==,type:str]
    namespace: ENC[AES256_GCM,data:jECn,iv:EsOQd1kYDeSTGBwzK4K6jinLAkV3yBSlonL4RXDq1SE=,tag:JsVEwPjZwhMyalwsdx8aPg==,type:str]
type: ENC[AES256_GCM,data:47EQuuCM,iv:QT2dB5RMNWIUlRtY0ZOzBg7OZfsHGxb/SaNnjCLmM60=,tag:QtgwFOIDgeMO0lhm9z9UaA==,type:str]
stringData:
    CODER_SESSION_TOKEN: ENC[AES256_GCM,data:V6ZEkrQXkiVlj1gobPoHsBkaFkj74Ir7YHvig0pIMqm9,iv:VigLiTEnJd8eQZSrqCoLW408DyJPwcuSrv5OB22hVYI=,tag:XiI29Cv0p1aWM2PSBp89Xg==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Mk44K3JKc1hoNFFMaExo
            TCtKREF3NGE4TStDempKUGZVMVozRUY2S2tRCmIyL0tOeDJCRituam92Umg2MGZn
            M3ptdXYzSXJuOHFSdEM4SjJUWXQvaUUKLS0tIDNwYUdmTVFvQm9hakF5eE5rLzFU
            Q21pRFJpNUhGTWoyVkRBVWlPajREalEKdm3JMBzJBie5fDN/eH4Cibjq2S97jhEQ
            PMU1UdOP601oNoEIs4xxH34yVcpbVpGwxGXLsBRY+4sxMSrKrTHsUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T22:24:03Z"
    mac: ENC[AES256_GCM,data:zgdzfSsUn50AHyZguljnGWGsnZ/aa9nNwV8ikD2Q+VY6GuYZEi8GhbiB+6iSyO2fBJR0dlw0Y7j+jJhi+QtsIVYgN8goXcyvoQtwrKlBUKpRBx/yXuviukc6RhvAd/ynUXhEiS69a4ZRzEG2CVl3Q8NsW1I7rK7OWJmD0wXbxqM=,iv:oRAUAbCAoSIPb31+/98c+4fjpnETMjIyqfRY9r5Q+Tw=,tag:OI/MbNmx9x+Vp7di9tmxhg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
