apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - coder-session.sops.yaml
  - deployment.yaml
  - httproute.yaml
  - n8n-secrets.sops.yaml
  - namespace.yaml
  - postgresql.yaml
  - pvc.yaml
  - secrets.sops.yaml
  - service.yaml
