apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:YlgfKvMm4yNSSLddexhu5UTBYk9xqJNHF5sQ8OkX0oW/CmFIYFM4lm3Sfj5QUXGtog9Wyx5BQH/nV9j8A+QZPw==,iv:WxpPdyqWnR9QlnOcLRX1KAdxwqPBu/nYiQNcIKPIDrw=,tag:08fyrsvi70dB4zcxCZxgnQ==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMkw1Uy83dnlVeVdrZEdO
            WFZaQ0VaRVYyYjVqYmVNamJubFBCdzZWbkg4CjRoWEdMcGVubCtUMTR5clN2Y015
            YkloK0dFeVdiamJSWUdnL1IvdGdyMEUKLS0tIHppbVRIQnpzNWJPTW1EeTJleDVt
            VEZDZG5maTdic2diSjRSajlMbnZvQ2MKB7MTmuhhn1z+V9XFNWnF98Qj8CPAWQts
            6zEnJlo/OUGw8Xli2xACNdhuDV4MQAyu+MZWZdLbnYc/VhBjLYEAUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T21:44:16Z"
    mac: ENC[AES256_GCM,data:e4lDcvuz8JxnPWTObh2JmngyQ5jWZgyGsO4XFJ27ZdS/J99Oinl437bOq87DP9avCzEQr/Zp7883wVrgil1aUy7lBX/3PAu8waO9539aeMhIQaPlKyr1KR7lZKQCwrObYFVB+MR67E8KnbLAOteeGT6e+tU8xH6Hzr5Zl7lJhAs=,iv:Ry+dT7MKbI6CsyCDlGnUSM07vQdKpnbbBV2VxOBx2xo=,tag:/X3dPU669T66gWqeJVs/2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
