apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-r2
    namespace: n8n
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:/jLPiNP1QcX4xXT7nEo4y+TxyDc2mWXv5DND4sEVMgI=,iv:NP9wrst40xkU1h3jEGS3Nww6lr0mhPrLWrdMAMMxeJ8=,tag:M/c9oLjD0e0tHfJ7EiKX2g==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:6Q/xjm9TG62nxBG+E+Iv75dWmWqFFfiwm2+jIG1v5D/1UcGmkWKWjT8eReunqZzSjJ6YQfb10aMw7d6K6Ej6UQ==,iv:oEjuhjMbc5xa/TT1pKPLXZleDq+B//GsRka0chnVDJ8=,tag:rivYzIlrH9OsQM+E+scwbA==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NHNudkJPSkIvcFB4MmVI
            MmwyVEJicTk3a0VKbzFXS2kyTTVUZmNEdGdFCmYxN3NzK2tZeHcrYzZKSFFNanNL
            N1dkT2VQT0k3VDhxWnc2NFc3QUhHaVEKLS0tIEpMYTNqMmxPYnJHczJmaElSS2Rw
            UGJkeE9NNEN1cDl6UE84a0R3bk5Fc2sKIgoWvFFme6Q3ZWOYVQ8pBrVOfpxzIprn
            26z/Q8ypdO0J6Z4mi9f7rUj4KJnMSTng9DqW+7MRKwnh/gDZBBiZqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T02:48:55Z"
    mac: ENC[AES256_GCM,data:OFgwz0+o6uFeIDf40COkNVTXfOClq/ZoAl/zifrsj3sPumTHVxnfxjdxSjpOj1bxL9KMn1l3eEAkFbUQjflX+l2cIKl+ikYJcAc2nlDYjRDI8De7Nymo0tXmlJREmg1cbczf+X6nV8DcL05bxLS9NGc5U+KLLU3zpaIS3tMwJmI=,iv:jQiixNaB461OkItsPgzI//owASaSVqvK03Biw3NJh9s=,tag:s5LaVIrYhYl3O0J30pSLKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
