apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs-rwx
  resources:
    requests:
      storage: 1Gi
