apiVersion: v1
kind: Secret
metadata:
    name: n8n-database-credentials
    namespace: n8n
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:jab2,iv:sphzBlTs6Ef1TcmLJmvUfdkYe2XcNTjtdMbJggMtRhI=,tag:nzTY8tJoM4ykpEuJSCRP9g==,type:str]
    password: ENC[AES256_GCM,data:+oXhTnDqvwRp+Lyn6FGbElDtizznorZC2zkRKDwbjv8=,iv:kfrS3sops1KxUBwE2bNtIEUHOfaYDVroM7XUQMaMjO4=,tag:AQ/LTl3f658mtXAlrcSEAQ==,type:str]
    database: ENC[AES256_GCM,data:f7af,iv:T4RaBWbaAMwXtbuST+rBDxrvlIutYsArlB8mlXmD3+s=,tag:naY8JZooXO2+PSLkT6XehQ==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbVI4UEQyUlVoRGxxNGt3
            cFVmZ09tSWFqOFdYQmNmRXlzSjZhdE9sZ21JCkk5TGtGN2p1TWlvcHE2SDNTOW50
            eGp3RWQ5MkloNU1TcXFiYTVvRzJQbUkKLS0tIDVoazluaU94TUsySTdYTmRMUmpr
            VUVhOWltNUpxWjJRTVZaOWJZQm1RM3MK/YvcExww+FAXVqzTL1Wqx+I82ZRilGhD
            cPiH8Kw4Qvt47sXQ52cYoyEWDiWClyTRweyil/lRXyFOS+6JiIuHFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T21:44:16Z"
    mac: ENC[AES256_GCM,data:1rUuFNHCKeoyctUu0KBCDWQGCLykNY/u0ykT5WvOdjsFgKWpb+QW34W2ouQ/UsXHrQZ6f8wSVDaOt4MyEtC5AGNrS8WCgOO9YVan4MBXJD1tARw/VwdXede8BHhJli6IM3MU7SOj9PhIkc600wtR63WwrnQd4okLYMmOUhlcpb4=,iv:JYxxb1AZtyZN5PKpQ988pucEm5NOTFiUvx27D97qg58=,tag:OGNSVlpNoeAVRHlU2CVqtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
