apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-auth-pvc
  namespace: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-cache-pvc
  namespace: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
