apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secrets
    namespace: ntfy
type: Opaque
stringData:
    ALERTMANAGER_NTFY_USERNAME: ENC[AES256_GCM,data:F86gtycRmw==,iv:za/kzqSBmUtdt137/tGaZJZFaPycwHKKJQ7EL6kwKvw=,tag:d6lFygZjn0X51CuD3aQHBg==,type:str]
    ALERTMANAGER_NTFY_PASSWORD: ENC[AES256_GCM,data:YfGTBku31sp2wYyfsdQ=,iv:lNNS7Vw8u/SPjsRGqXzcSPE/osi6QEoF5i3UVr8k7/A=,tag:x0l+6CmQjg9ZP+ACuYvvQQ==,type:str]
    NTFY_TOKEN: ENC[AES256_GCM,data:/HEb78dMqN8jtFjF9Vb5AInE7zHtQn/IWtfC0XbmYUI=,iv:S7PvueaS+LoJ9lfgXPvvceO7uGPWotRVYFj9dfcCAJ4=,tag:bwHSI85Kz5PCp0MsYtpEUw==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSFBTR0RDRVAvNm5KSEpE
            ck5OejAyMnVjaVFkdk5nNU02Y3gyUDluU1U0Cmcxc0hwSVoxKzVFMVdvN3h6eW1H
            VldqVE1YR0Zib3M1azU1UUxpSmxWNncKLS0tIHFYR3J6Zk1Xa2VsWTdrUFo4dWRT
            M2Q4MnhIQWlUL2JvVGQ5SkNOakRSeVEK6b/YTswVF298lx3OKJtZAK/7RAGhsXyZ
            QpnjGmTytX7wkTziqETo9BqQkz/BV7las7/jz+PQ1myKLr3z3OMggA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T05:23:21Z"
    mac: ENC[AES256_GCM,data:fwTlnMJvlo4sbCrfZcadh1BMGfHyv4wxA7zniNbKzGWcEIgXFIIMuDOa719l11fM38WgVi/8i6ew0bYEn6SxSEj803Tv6UUBZQfTjAZ8WEcSGrricd5GpPS3Gf5BAa8sWFH6/Jgf38cWFgZe8at+9vR+R2VyikcXYRzu0znzIg0=,iv:pHQdtb1PPbJ63sDQShZWQgczKv2A6enxhg2u2XMCbKc=,tag:svoU1Kru3xOLe/NrBeDn3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
