apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars
    namespace: flux-system
type: Opaque
stringData:
    DOMAIN: ENC[AES256_GCM,data:kk3qi8gfw9MK,iv:79lm8PrCGu9k0ghTO/U8hBcUdXNavJweYRhIf2DUS4c=,tag:fHgPz7wbcCQjFizDYSLo3Q==,type:str]
    TAILNET: ENC[AES256_GCM,data:VJBYIK3OnbgI1Aycz1pfds6b,iv:n6Dc88zv95bA519GwCmMZLDEK5DBKFWA6DEpnz/zvVM=,tag:Jko0S6BDf8anlHXr5tOcCg==,type:str]
    LAN_PREFIX: ENC[AES256_GCM,data:mYXsBsi9yhaws60=,iv:NvlfVQ12lOIHpoj1Xc3NMnojfVimV6wYcEgxQg/DgUI=,tag:N8Ii+YQYwn5EAET8UHbF4Q==,type:str]
    MGMT_PREFIX: ENC[AES256_GCM,data:zKTkSLGUwfgo,iv:+t4CEba76+XF5OZbs74sjpSOC8fSgWcTTJWmalvy1l0=,tag:ECLJ5QQx/c8bx6PXp1fCDg==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWjJmdi9IK25rUUdBRzlC
            OXFmT1EwMklTOG53TEgvZHZobm96MGJWckc4Cjl2M2JHU20yVWJ3RUZLTG14ZllS
            UjkvV2M4K2VUOHROOWJVMWdCVTJtK28KLS0tIHVLanE1UCtwMEF0UTZxeVdLdS9h
            M2QwV0EvVS9hajhJa1QreWpjejExVWsKuRkpBibjuhxj4/9Hl7ObkbRDAp2NYX19
            6TmykV/JcA1x7TkViXsvG9fDohekDSNoFoEtOr1aH4jhKJEINal2QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T01:30:32Z"
    mac: ENC[AES256_GCM,data:O7wNH8amoxZplQC0FndRetFfdKhNmMEFLZAk+6xaDzsfL3uk8d91l/4zYY/un+AM9//yxJSooP0ss0ZLHKwgRqwgeYKKECc8P2ezsK6l24AhfHHntcJvorlFjZC/GCi12Rp+TA8+EOR7fHdnmntxqyW7g09fvrangSCQaglhyV0=,iv:tIWfOsxduNrCrGKYNW2XfKQPe2c/TeGDqXBr52MIhW8=,tag:CFK2/318GvKBVY+84EaPqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
