apiVersion: batch/v1
kind: CronJob
metadata:
  name: adguardhome-sync
  namespace: adguardhome
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec: 
          initContainers:
            - name: move-config
              image: alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-c"]
              args:
                - |
                  apk add --no-cache gettext &&
                  envsubst < /config/adguardhome-sync.yaml > /config-target/adguardhome-sync.yaml &&
                  chown -R 1000:1000 /config-target &&
                  chmod -R 755 /config-target
              envFrom:
                - secretRef:
                    name: adguardhome-secrets
              volumeMounts:
                - name: config-volume
                  mountPath: /config
                  readOnly: true
                - name: config-target
                  mountPath: /config-target
              resources:
                requests:
                  cpu: 50m
                  memory: 32Mi
                limits:
                  cpu: 200m
                  memory: 64Mi
          containers:
            - name: adguardhome-sync
              image: "ghcr.io/bakito/adguardhome-sync:v0.9.2@sha256:fb7224aeeab74d68990c3ecf51594a6f92428fcc93c7a162c3bc221e77a49025"
              imagePullPolicy: IfNotPresent
              env:
                - name: LOG_LEVEL
                  value: "info"
              volumeMounts:
                - name: config-target
                  mountPath: /config
                  readOnly: true
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "250m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: adguardhome-sync-config
            - name: config-target
              emptyDir: {}
