apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend.yaml
  - backend-traffic-policy.yaml
  - certificate.yaml
  - cronjob.yaml
  - httproute.yaml
  - namespace.yaml
  - pvc.yaml
  - secondary-httproute.yaml
  - secondary-pvc.yaml
  - secondary-service.yaml
  - secondary-statefulset.yaml
  - secrets.sops.yaml
  - service.yaml
  - statefulset.yaml
  - tertiary-httproute.yaml
  - tertiary-pvc.yaml
  - tertiary-service.yaml
  - tertiary-statefulset.yaml
configMapGenerator:
  - name: adguardhome-config
    namespace: adguardhome
    files:
      - data/AdGuardHome.yaml
  - name: adguardhome-sync-config
    namespace: adguardhome
    files:
      - data/adguardhome-sync.yaml
