apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguardhome-secondary-work
  namespace: adguardhome
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
