apiVersion: v1
kind: Secret
metadata:
    name: adguardhome-secrets
    namespace: adguardhome
type: Opaque
stringData:
    HASHED_PASSWORD: ENC[AES256_GCM,data:C1nZ/3vI7JiXJgafVPC88EmiwuPLjtOM0DtidUdXBKDWYsoflEsttcEiJZlF1ePuTSj4zKC1ySp5Qstn,iv:5i3epNsPl60ei+nDPlp+fsaURHh3elluZmteAWASmTo=,tag:Lwp++1PhYp6nMdlM/TZQ0g==,type:str]
    ORIGIN_URL: ENC[AES256_GCM,data:6ieZYg0Q4kigalcTmtSOisJlLrf1emLT2AvS,iv:vwsbFJKrXemWhmN8hohXFRVhfez/nK23Kn2ZNv/tDoM=,tag:+0ZvDIc7qEew7qRvOflz3A==,type:str]
    ORIGIN_USERNAME: ENC[AES256_GCM,data:QHoP01qAdQ==,iv:4F5meWN/xOwrlkw6VcZGckAx6eip3sw0f9g4b1QHoDQ=,tag:LhoZwjwldMyXJk8raMmtPw==,type:str]
    ORIGIN_PASSWORD: ENC[AES256_GCM,data:6gVE5yCy+Uv0wdXtLxhsA2UUswU=,iv:8oKb6UUt7f7U9ad5AF7bjPhsrE5wbUbIgxIlJ1RY1WU=,tag:ZioFXLTTRnZ9Wp+zJZLIDw==,type:str]
    REPLICA1_URL: ENC[AES256_GCM,data:EA2LTwLFlYA+B3cDU0KjyqthAfXS6eirHKgwXt0=,iv:MrZQpy06G88cnwjdUNgKNvAKXVEVOU+WSH/q6YnOnX8=,tag:yjtN38vEmYbS37BQU6jBLA==,type:str]
    REPLICA1_USERNAME: ENC[AES256_GCM,data:MQopXkMRIQ==,iv:d0F+niR+JTcIv7hnqSl/MXYskPRWolHJekdLPIjv0+E=,tag:AsAN/BGdXkkUiKwvpUobgw==,type:str]
    REPLICA1_PASSWORD: ENC[AES256_GCM,data:HwHiq3ngcMsGq9npkctgky5njGw=,iv:4TN2+CuC20FRFxfnbn3RQBcDzBESQMoe0EMtWxCihUo=,tag:YAK8PH6ZjeL3DZHq2Jod/Q==,type:str]
    REPLICA2_URL: ENC[AES256_GCM,data:/WAMX7tJmhM9GXUxdYnaM6/Uhuo1y6JPnEI15Zs=,iv:veUmWSk+uJF4sYc7Mf9SK2Ygu7ha20NNYJpo+SEXvfU=,tag:DS9FImoTRbyZ+E1iu7ol0g==,type:str]
    REPLICA2_USERNAME: ENC[AES256_GCM,data:TyzBc53RFQ==,iv:e6AUUVEHmXhL/2VjiPdp6TVrZn8WzRyRz6TcWt6e6K4=,tag:mFFUVdg8X6p4P9eDKNFPYw==,type:str]
    REPLICA2_PASSWORD: ENC[AES256_GCM,data:iYAZzGxwWwdkvV8P8np610auWcI=,iv:0QDzRwd6PPfkqZwtpkth00sEBU+xt0KSdEVdOaJUXBg=,tag:SQnJlSXKJfmS6at+6X3Gsg==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRDZ3NnhiTlJ0anpEMENX
            TnpUZlhKbUIrcTYrbmxsc1FoaEM3NmFST2xrCkRsVWZ1alZqVmtVZFcyWXVxZFZU
            VDZ6aFNwaUltRi8weXdITE9vUWNyaUkKLS0tIFk3SER4T3o2WFZPc1BzM21Uak9z
            WS9KY3RxdFptN3dSamN6MFNITTEyTU0Kn24T4ezlzIdMHITyus6Bp2LQvrJWARiN
            ntjF2IXczAHJ530A/kLm6oUrCXCn2xJcy3Gjr2UAfiLm2vwMwPKHyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T14:56:37Z"
    mac: ENC[AES256_GCM,data:14fD8++d//x2H1Wa7tHw0TC1QuQhmN+P06qbCYpZOoXvUNspmiGafVB0o+yyf902rJEMRN2z8lTuEbiRz/iRUqOoU/LQ99ty6GiI0+9yNTreDRLpaAsnetRkoDBrn+lnaqMrdHxGd870BQxB/o3dB6xX1P/Qfc0mpNLY5DhZ2eI=,iv:VI7zpDl//QWFz6cMyc5C5zCYit9ApXKC2utU5DgUyko=,tag:JO82k/8xoa4rLx9FyHhDOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
