apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zeroclaw-data-pvc
  namespace: zeroclaw
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs-rwx
  resources:
    requests:
      storage: 5Gi
