apiVersion: v1
kind: Secret
metadata:
    name: zeroclaw-secrets
    namespace: zeroclaw
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:9blaXMSy9H/9TTttxWg2QsGLArckSJ+PlnLf2q7GBaRuCsS3h4iz,iv:DoJVmj5UPTCLfg+GXxWzDBAasAgf/GXtQ+lrzelW5rI=,tag:OenyO4X+H4QHGP7cOqQPdA==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:t3aSDzFSCHC/8jSFx+rVbgb4s5Su7p07ncKx/IZWpzQ9x6/UWpkin4N0x3SV2A==,iv:UB3yRb3W9+PNVxEEHzVF1tFYv+DII68pop4GR7hjdi0=,tag:y9/D/oyzsonbpnsJkvf6JQ==,type:str]
    TELEGRAM_ALLOWED_USER: ENC[AES256_GCM,data:OTk13agX39LDCxyq,iv:mdLsl5n0Z5QM63HM7oLPdLUL9HSdFQKaIG2/69kxB00=,tag:Dvd/fWF/RavEGUxYwiIRgw==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMURJWVJGcXNLcE1FNlpk
            bWdwN3J1WmRBZzNvUllNejBzL3ZIOG1qT1VvClh4RzFXWEp6QUtLZXUyUHhBK0d1
            ZUtBekNsNVZIdUw1NVVRMHlBZ3FPdVUKLS0tIGtiajY0bS9oMlg3NWd6UDFSRGdC
            SE84NFRqNytVNnJRNVpVMzdLOEExcE0KTD/TQ7nxdm41khczsIA9MT0gaHWFM6wz
            Q31huT+rsAcen7cFo3E3milXCaaKuDAEO9MYfqXsyYJeqD9lwK0l+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T19:23:10Z"
    mac: ENC[AES256_GCM,data:nfR+Fa3NLOjgpbG/rZncnNAvooRIKgazXM17FbBxUB6GgCIv4S640DQmEPqF3zSVnU+ynVzolFvqpG7rsH0zZ/OC/ckRbqLG05WNtWq5xyNT92avHcMMQpN1Caefyy9WXAJIv3/NSd22SECucFbiN8NbBKwYry2/RA9GZ5y1gxY=,iv:OaUBg721K50K+u2VJO4BonBJf7Un45qQ6M1vyvZZVlA=,tag:Bo21A+t1gNFz/5w3BtNzoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
