apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blackbox-exporter.yaml
  - graphite-exporter.yaml
  - helm.yaml
  - httproute.yaml
  - namespace.yaml
  - pve-exporter.yaml
  - pve-exporter-secret.sops.yaml
  - proxmox-dashboard.yaml
  - secrets.sops.yaml
  - truenas-dashboard.yaml
