apiVersion: v1
kind: Secret
metadata:
    name: pve-exporter-token
    namespace: prometheus
type: Opaque
stringData:
    PVE_API_TOKEN: ENC[AES256_GCM,data:slSfKNyya2K9S8a04g3Wo8A+L3zh1H0ZWvf6yx0OitYMep6v,iv:w/ANcW3nLhIhPdmFuFeRffHP3gIeTsEMlP3sDCULg+I=,tag:Oy8DWdI9Utj12+JJynxWGw==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a2x6aUFPSUc0UFYrT2pJ
            RkxHL05ZWkNKY0x6SnlWK0IzZmlCNzJIb0VrCkY2K2ZDekkwN2F6QjRXc1FTTS94
            cnUxclZJVWU5aU5rQnl6eVV3OEFzMmMKLS0tIDhaWk43NmU0K2l4NkZZYTVzZWU4
            Nno5Z3I0S2VqUGY3dXorQ1poS0NkM1UKup/3hITSdchp8ptxaIidQuea+RD4a+OV
            BOCVbKXG5ImeR/FyLdt5FeVq8CoDQO30sW5sPRXLkk5u5FkWgUoV9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:46:09Z"
    mac: ENC[AES256_GCM,data:ivPjZZnqrhtO4k+quk3fWl6KKLndl6YV/MAuJr4s2PcoCenDLd/7HCWaFiSjf84myItd1SqJO6drRh7ijda1xYkEmXbpVwBTKsIPiwEVVkn+uhjylqJhdMb48JXvitVnAZl5rofkyFQDt+TBYB8XMaoL7+nTxrrfTMOwaAXGi94=,iv:OTihx7oYwiiuQzWF2yNqu2r1n+nbkpfQUSArIySDipY=,tag:DjXGBSHQwXLzN0jL6Udqtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
