apiVersion: v1
kind: Secret
metadata:
    name: prometheus-secrets
    namespace: prometheus
type: Opaque
stringData:
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:8yC/jQ089A==,iv:cet5CnhDTrk9mp4GbqumUUYBX+3aQ+Gu69tWEqKkPtc=,tag:g7EjNvHvTy8Hjc4D4ybxbw==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:rVlmvwJW1VTDwJrRYts=,iv:CJKJGDAYd92JMnhTqq9eUtX86HTyIFTHDNTchEG3n8g=,tag:vm0tEw/BrhVBrvu9kc14WA==,type:str]
    NTFY_USERNAME: ENC[AES256_GCM,data:zwK1Jc7sPg==,iv:XnG1iBWbrWMqMh8M1nAgRxf6+nDXpl6WehsNsjIx7OA=,tag:QFAF1hSkoxBjIVgM5P2FAQ==,type:str]
    NTFY_PASSWORD: ENC[AES256_GCM,data:bUH8+XJpUWXRjTVpZvI=,iv:Z+pqeqWnhXLbAgdB5y2yCdfYFL8Gdw+aHquq6sBotFw=,tag:2DuhVsH/aWN+jJX3qKiMRQ==,type:str]
    alertmanager-ntfy-password: ENC[AES256_GCM,data:8aI/HGmI9Cu7FdYs1TunEe6gxX5/3NU=,iv:q8WtBYSFfQdy0knUvgIvRGzKL4PpfqZo5EzYdTyQqww=,tag:pz/fV17Y/J1LSmMYTbi63w==,type:str]
    HEALTHCHECK_PING_URL: ENC[AES256_GCM,data:1S38TEGpQiPs+aNkgTkqjKor7jDJ7nmJcml8yuNGBeNcW42EUHrbF+fd60V5y5ulbhkrkr+1QwA=,iv:nZb3LBtwlXrILg3EpRIglpfyVUPG/qk3FV+Tqy8F278=,tag:APdvMkcwQQblgqup4qiFDw==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZy9jTXhSMWNVMXQ1K0ph
            MHVoMmkxRTBFeE5iS0kvS2c2ZlFVemlvRWtFCm80elRaN3lMSHYrMlVxTXN3bS9G
            Wm9GMjlkSzlnN2V5a2JZOUNQQ3JPSjAKLS0tIEh3bWg0Rms0ek8zZlZDbW4rREU2
            VHUwNktFT1RVMWNJY3BGT01FQlJHSUEKO8LBrtKM8R1LtxSPMX7G5Ajcc1qjPkdb
            Q/IHVJZ+gZ54OkJOz5Wu7vXr76SLmnvwJ0iu+MavgngxqPh4WuHDTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T23:25:27Z"
    mac: ENC[AES256_GCM,data:96XgDrjOoSBMVulQ2cyevRB+YrYsneVVd6cH+yd9T++I+VT3VfErDiylUSYc4uKt0XBRSt7dVbt/f+4fZgEAt0yXi8becUd9VoOb+EMegz1MYp5Cg/Yxa21G9jzayTfbU+jU98SVaeY6oBozGbCSLZcXF1MmIEQEG0cJdag92DE=,iv:zzumhprcZlD3YT87A0qba6193BZ0PuVHAcgIbSd1gHA=,tag:E5sRLuATq2BIjhdkiNx6Aw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
