apiVersion: v1
kind: Secret
metadata:
    name: truenas-api-key
    namespace: prometheus
type: Opaque
stringData:
    TRUENAS_API_KEY: ENC[AES256_GCM,data:S2wjGElLyauEfX03327tJb1x67xYVmsjCnE7Bm7hN+3JqM/fGJAiEBrqzUCjDYZ3oVsybcpfAPVio4xyp8pDcDkY,iv:z0XEnUJQPGJS76mg74c1Um33ANAKoKH6VOAS48GUwYU=,tag:RAouH7q6XOAQM99F1LAszg==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1L1BVK2twOG5qNmN3RWlN
            RFUwbGlWSTYyMFlBaTRKcS8xUzBMQ1B3TkVRCkphd2czV1BodmlHSlFwTGpJZ01l
            dXJUOC9Za1Z3SlRjMnc4b04vRThiOU0KLS0tIHFXRHBBWjlRRnRBVWoraHF1a084
            WHBDZ0R5M0FNUFNtNSt6WVpHQ21jRlEK7qbC43GSCMbmTAvaOqnmbw2aRlxsH2ee
            fva5RC24bPhERAifxivyi8G7YaRdVuFaenRVUGfCZRVBkkbzavGCCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T19:42:10Z"
    mac: ENC[AES256_GCM,data:AddCETpdThPj/qz5Dh9UMEOZqsyaaDVOf+RWTbDi9h4GjasxxmEMrZU7coRRlV/T4L8AwAmfPnMfe3uHNn8qeDVDanBvNKf2WfWPGui/cgE+k2DpU2nKkHlc8NI66SLXOIZOnVTWA0VkpTTayW/8sONTLIVF/LoKOJjspci8QQY=,iv:i893b/p64N2ETo+0I46h2npev7q/Zkh9ntXVO5eB3L0=,tag:DIIjHKoHsfQVSGCL2JsOhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
