apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm.yaml
  - httproute.yaml
  - backend-traffic-policy.yaml
  - namespace.yaml
  - pvc.yaml
  - objectstore.yaml
  - postgres-backup-secrets.sops.yaml
  - postgresql.yaml
  - scheduledbackup.yaml
  - secrets.sops.yaml
