apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-r2
    namespace: immich
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:k2u54KlIkaXZW5/pE0OrS2e6ooSblGbEnw3gKLAQMl0=,iv:N0zNiI3QEWNK0Dx+aAcfg2048o7gnhR6K/gQD71Gbck=,tag:eJTP+n1nxIQ/fptqvtTyLA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:S/gMy6aJBgKkBltzQwJe5gVAwaAq/Mdmb4AiHnjut/UFrDSvi2kIhYTa+/lEZFTVt0Nugfu+CvGkwory32PbpQ==,iv:oWeNLDvn6QvzilSJWQS6vUIwT7TA1u/8VQtL5oNs3Wo=,tag:2/DxBhXDh2O9jDxYNHO0Tw==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSHRpOURTamRnRjdRN29S
            U1Rad0dUTHhVbkZpd0JKOFQ1cDMvWHFBVkFnCjY3VFBwcEdNZUw2WHF6NzY5dnBx
            MVp3RzdqbGFjL1JzZFBIUUtQL29od2MKLS0tIDNLc1MwNzVVWWxHdUtiSGQ5Mnlh
            VnVrdkgzM2h4bTU1VEdWbk53cXFGMTQKRzgNMVL7y8iXOvAV2A/ZZzXfYDqfbNk6
            MxYjUtQG1aDlyiyCfSKYWO2cj/3eTztTlyArQdTHu6B05k7xvKQDBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T03:11:10Z"
    mac: ENC[AES256_GCM,data:VpD/twlsQyC0qre+FH2jI+51diHFQ1yHBZ+iad5v8/4QvdmPsY8vbT/eyhYx6xg9/4bTD+U+5Kv1e36U6ATcpEf9gsUydu+AX0Atr/DTfZxcHRYcrQsgxdzMHmqSdgPr4WpBt/GPO2Tks2koOt/ZkQIhRur30Osv9IRModZIIdk=,iv:IpB0o9Hjj6V5AvWRhXrytXofbhBPrntJ4oUJiBc82Ik=,tag:qumtUwW7LB99rfKXfX/uLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
