apiVersion: v1
kind: Secret
metadata:
  name: immich-database-credentials
  namespace: immich
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:vw5uFkoD,iv:Ay940rdvGqa6RLf3kDxlwBn95NgmFnED4bHgGZgfCH4=,tag:1wXSI85E7XsFAHfb9P9kkA==,type:str]
  password: ENC[AES256_GCM,data:XjynI3gWQd1RJ3osIBk2GJR36WzKLuE=,iv:+33sDOuc0U83R4tAtYvWTi1zhUUM3c004FYwM8SYkkQ=,tag:wv3tt4URIazlffkW+iZqoA==,type:str]
  database: ENC[AES256_GCM,data:OKqhpe53,iv:2UzZW2RK5UM7QaCdOa3hxqewWlea4PJHPlYqSi2q84k=,tag:GLiZjCFsdiS3EDrk/fuf1g==,type:str]
sops:
  age:
    - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeFBRUU5kVG1yQjRiMkJW
        TXJZNTF3TjRlVlRjWTljSWpOUDlLUTl0MFRVCnd3Sm5kRFM5QmpyYy9VNVlPOG5O
        SUF4UnFIM1R2WHRJSnRhMndQSzBNbzQKLS0tIFZFR0tzZGhNZEhTSENYS1pqZlFn
        cTAzWUVxdkpQaDQ4WFp0V0ovYWM4S1kKme5gdGXvYcOMk20ROCaRbAm+1VW0DX8V
        jFjg21Y3NOctZYcisYZ0UmXdzhyXkJkV3yks1k8fT7Ejmp1/IWXkDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T20:10:44Z"
  mac: ENC[AES256_GCM,data:93mvX4/SWe2LwaOdHLuFSvFp7C/6JSM5QkBYbBesaq1TDSdlOPUhvBJ8zBnCAqwQ6vwVLdO+8fG9nhIx5OLWUA1KO1qMVrJr0oxF6TenMdnN/lf9ywbGWl8ItPUVwtrO7UtgWgP2GpkHGxoe4363KDKogimkFVEz0Ii4m7/ZsBM=,iv:9pd+xyL79sJd56mgX8Pt7R/c1e86EsMd7grAASyhWsk=,tag:VyOho9enRl0IFEotPzYDpw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
