apiVersion: batch/v1
kind: CronJob
metadata:
  name: ansible-configure-image-gc
  namespace: ansible
spec:
  schedule: "0 0 1 1 *"
  suspend: true
  timeZone: America/New_York
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: ansible-runner
          containers:
            - name: ansible
              image: ghcr.io/jcwearn/ansible-runner:0.1.44@sha256:8eaa61a36f71e62a19958419232b81197fd471bb46b877e14a8b338d84052fc5
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 0
              command: ["ansible-playbook"]
              args: ["/ansible/playbooks/configure-image-gc.yml"]
              env:
                - name: ANSIBLE_CONFIG
                  value: /ansible/ansible.cfg
              volumeMounts:
                - name: ansible-data
                  mountPath: /ansible
                - name: ssh-key
                  mountPath: /secrets
                  readOnly: true
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 256Mi
          restartPolicy: Never
          volumes:
            - name: ansible-data
              configMap:
                name: ansible-data
                items:
                  - key: ansible.cfg
                    path: ansible.cfg
                  - key: inventory.yml
                    path: inventory.yml
                  - key: configure-image-gc.yml
                    path: playbooks/configure-image-gc.yml
            - name: ssh-key
              secret:
                secretName: ansible-secrets
                defaultMode: 0400
                items:
                  - key: ssh-private-key
                    path: ssh-private-key
                  - key: ssh-public-key
                    path: ssh-public-key
