apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - cronjob-upgrade-hypervisor-01.yaml
  - cronjob-upgrade-hypervisor-02.yaml
  - cronjob-upgrade-hypervisor-03.yaml
  - cronjob-configure-image-gc.yaml
  - cronjob-configure-k3s-shutdown.yaml
  - cronjob-configure-node-sysctl.yaml
  - cronjob-configure-lvm-thin-metrics.yaml
  - cronjob-configure-k3s-server.yaml
  - secrets.sops.yaml
configMapGenerator:
  - name: ansible-data
    namespace: ansible
    files:
      - data/ansible.cfg
      - data/inventory.yml
      - data/playbooks/upgrade-hypervisor.yml
      - data/playbooks/onboard-host.yml
      - data/playbooks/configure-image-gc.yml
      - data/playbooks/configure-k3s-shutdown.yml
      - data/playbooks/configure-node-sysctl.yml
      - data/playbooks/configure-lvm-thin-metrics.yml
      - data/playbooks/configure-k3s-server.yml
      - data/scripts/lvm-thin-metrics.sh
      - data/scripts/pve-reboot-required.sh
