apiVersion: v1
kind: Secret
metadata:
    name: ansible-secrets
    namespace: ansible
type: Opaque
stringData:
    ssh-public-key: ENC[AES256_GCM,data:wwrujuR0ODSS9zMkaoN4HqwCoq/8XeguCd2Z7r7yLRO+RzdpyOIyycwThGYJBTZuHWx77IEgj7fQkFunxfOSnwv4E+Pzz7UX79CP+10EyO7k68CuOLCm/c3GaMTfS0AlrHTVGunVM4Q=,iv:CxmOhXwHeCr2kFoo01m6n5ZJ7Mm0l5d8uy6Cnh9Nc8Q=,tag:mjhP8RTaalhsAdD2E0qacg==,type:str]
    ssh-private-key: ENC[AES256_GCM,data:Wqxy3BfQBZWs36Fr4EfK/psRN2xTqiKk7vVkn/+CBoEA0jTHBnkCZx/YCEHm/XxAdRXYlCHwupvAcO0vncvGrNnh2fFb+dP9vTSo6MR1G445tHvZiM/DhXiuvyAKNNCcpyS/GnNePD/vKZ2FS9sywBoJRNG/vUVxb5fqgZAZ0W0Wk1bB4NeC6eYO/aluxwHeXzke+3XIWAL7UciuRABhh5WTChHyk+isJ3AtLhVoV6UG0X9FgKhIkVI6U3rTbrMMU6zMaGZ2QvkWOAGa49YE7UlmfZAm+D7iBfap7Yno7ntNa57yJTvjIYHQ5c+rg0WLG6vJVjyvaJHEf8PBnyBGXvBdoh9HXurR4IUCGJHEZ6oSwjZLPj7T4pRZ1kwJ434ji4Xi+f3V7w/uf2INjzAaBcRKJeGrgy6uSRT3nHdOxHNEkXR5MS6hAFOqrS6bT74pb+vx2dZOkdZcud8U7zZRJbtHjI8us5xeGW9LEs3ftu8hi6M00Nk0lqG6tRq8iOH5fdSXDxp7lyBtitEmiiC9A3dPIaZrZCFZ+oa6s8h+rceHcsU=,iv:S/hJoa9szCD1rVx7livlST24eLj6cKtF2/rMGGxjloI=,tag:hXnu0nQGuqtYTHFEe9aoQA==,type:str]
    ntfy-token: ENC[AES256_GCM,data:iEwcIEQguCkkEllNvWNctlO6i1bm63qJjXfKYzxcUh0=,iv:Vn5waJ7sQfJ9sqmlwhu/2hW/A7TYxM4BMZKkQi0z6bw=,tag:rAFuXGwkpO15F6b8p6NO7Q==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUnlnTEZMNG9jRkxodk1j
            dHgyNTFhNk5XcDkxRFAvUXp3bkdmYWVhUWhnCkpLbjZFcjBxVllYYmU5dE83Rko3
            UlNOZ1VxMUFDV3JjdnduYjl3bHlDcDQKLS0tIG9mbkhSOXZxOHlpL0dMMkhoaVhG
            VzYyN1A3M3p6bHNZa1o4ZGJ1eUtSVDAK5b50WX4eSa9IOvwfn30n6yY2h5SPRR6n
            cn1hLmbNPBNF0bhEqmhEFo8Q2TQ5m2nN9A2k9zv6lH/8YOs1jMWf5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T15:52:57Z"
    mac: ENC[AES256_GCM,data:ep+8liKB7TZqphba/TF4qJRXEFJeUnW8hso7jHI2OIRsFpG7CizPpThdeOEKHefUEJJ9vKMJGSSzxVJB12LU/yxu+UU6gWYFml9cUMDnD0AEy4yuG+tYSJkSol9VvKDNDim6TLpgwVVnPWDkkQh/xXFxk3dvIRH6gRPdPzbxhKo=,iv:jAbdiEImMtyYpBjtXGC/q+PJSLi+I486C12WZznNZro=,tag:5SWvbRd0QMLGKyD20I7dlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
