apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-r2
    namespace: job-track
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:yu1gfV4YxB/wrxvc/rIledxhKwG2+8YWMwgKDUwTvuA=,iv:+IcCl84SoYr7uhunKiMsnq09J9WNQgcqjJ2+7KUi++k=,tag:klc2vQcxM93bQ2n5YBsweA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:wqf6cN+wRNKv1U1RC38MnsFoVguUHkj8J8thZdKZy+L0vE10KFmuolzBTB7/dzhyOMNSUlrErX99ujzoH/3RIQ==,iv:ptBmM+vUrOkEjH+M+WxSIalL4ESBVhkyZYXmK7Nm95g=,tag:X8sbsNZzxpbvZ+pDlTO0Dg==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOWxGd2x4WnFRRnRXYmhQ
            YW9RMkZXSW85QS8xa0RjOG9GOWx0RHRpQ1ZvCk1naTdPSTYyVUlRUmV3SGJtNmE5
            Yi9uWGJBbmt0SksxbitseE92UlBJWHcKLS0tIEhELzRRUWZjTjlBMUdFVVNiS2NH
            VTFBRzMxQzZIaGpLMlMyRDd3L3VLbFUKFDJ/A5KOCiay807dI132302VG1qCyQYe
            QAqBmlaRx+4F22Cs0+GYZJgIb8R6hZ5mVA91MQJA88X3jEMFgD7DNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-23T16:14:07Z"
    mac: ENC[AES256_GCM,data:yHSuHVwgmfwF1bxHd5enEWq26ngTCtsY4jZVBPwpdXSsKOqdr1zOgqRLoFvYLlv9dEA9b2UmDQquR7Gp2TdPPCnKkq/AGoR2thCPzhn3ir2t04Lj5Dmhns+JL8qqw4M//18LqERMk+Q9km/Ty3zC7kuNtGl4JdXRzQGZdoHdqqY=,iv:CQd3Fpwgc5FNQRGzuW1APgE80p5k1tSzxVdIe9lz8uU=,tag:vh6knWS7+4XC4VEs8ngPoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
