---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-headless
  namespace: uptime-kuma
labels:
  app: uptime-kuma
spec:
  clusterIP: None
  selector:
    app: uptime-kuma
  ports:
    - port: 3001
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  serviceName: uptime-kuma-headless
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: data-volume
              mountPath: /app/dat
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: uptime-kuma-data
