apiVersion: v1
kind: Secret
metadata:
    name: cf-api-token
    namespace: cert-manager
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:3keiYWKvFqSTSM220G5K6xZqFgRP24tQ/eV9bo3nMNxzRtYlHBP8dQ==,iv:HznT/4QAvUhqcwKTaRAIi3aWaJzmJxY6ZWQzsXM04MU=,tag:gRcjYkG8+mu2YonZc65/aw==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScVdVdkM5Sjc1aXJMNHlo
              NEorcWlsVjgyYWo0UzJEL0RFb21abmZ2b1FNCm5EZllVSW9VamN6TnJ0aW5LUkN4
              UllvVXhhdHhFMGljSnN5S2VKNVplWUUKLS0tIDBWWmlrei84TERrL0FkZTc2Tk9R
              eUVCekdXamluQXFqME1mVnVTUHJiZG8KNuYiWxnYhwk4Dk2eW+tacN/4dz/auuEx
              P1ae8XD8WvkIMeRSbacOtNCGJHx/QITngZ34kNvlqdEicqx83QNUaA==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-21T00:16:31Z"
    mac: ENC[AES256_GCM,data:KKjLMgwmXiPhTCXqNxiO9hXbbyvk9bWQVpJfR7C3oOyIAcT7H2iZxW2Gx5k08FbTpT0M2v3WZMYV5YHyA2sX/UmPYPqt25C1Etd9hPudL+u45idT3U35KtWUSjccawxHdEeXV9IcSYwyPjepY208gh5sLc76rQ4w3f7WFvzESXU=,iv:zGf8CL04+yghQ1W2oWdHDf2MwhgIoeFUyw5IOR3s8hU=,tag:uLkYRNWQ1VzA4ajrfsfP8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
