apiVersion: v1
kind: Secret
metadata:
    name: cf-api-token
    namespace: cert-manager
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:31u/Q1TMxnIqdp15KiuezEc+6z8TSZqbvLQHsxJ4TZegJZPeucL1MYhcNSmiV/1IfvOKoPs=,iv:gPoDc3zWN1uNURbL6K9Vp8B+XhsHa3M1eixmaz5+Tik=,tag:lBYF/6NgRmb7MFd0+h2Qfw==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeDZQTUVBV2JMdHpCenpB
            a1NEQ3BmczQ1ZEt0ZnlrdFRwQnU4SGZwUlIwCnBYKzFJYThJdVRuMk42NDh0bUZi
            Q0JWRkM5Ym9LZElpSmlhdkNnMnVHRDgKLS0tIEIrTUZQRDF1ZGdBMXZjT3JHdEhC
            MzhtemtUc3FRbTVGcndjVUd4aG9OTUEKi7/pyhxT2So0k+m7TOqewBtW6aSsMpfb
            nOs4n0LTJTurh1eivAg0R6CE9PSid/d99lCOjM4qnuPJGeyHgV7vsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T21:37:04Z"
    mac: ENC[AES256_GCM,data:KHzvffshwBqkvpMfNDXaLuHGHbIFIZgaOFowKgeQA/+f1DR0zFgVC/7iIN5gIKmFkKyXshjq+pK7n69p3mdPuI6R1zeN0nkgHLaib4N3HTHswc+OawhPWForoZESd4mxxV2YFSTEKzw0zYHjXZooQpuD7BMve9sH7PwRlJiqv2U=,iv:pqnqHzx6KBtO4Vff0GuzafSHeiAmchWIOuptOnBEpOw=,tag:XAO3nqNBCxuip9DVOJeNZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
