apiVersion: v1
kind: Secret
metadata:
    name: flux-webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ZMCxFBpc5WCRnInzz3tASgjRyboNbfYd5dYYFlZHQ0THhHjtaiD1opvhwPXGB1l4X7eu+yNtopxXNY7WJOZGrg==,iv:RRCBmB81RE7OFFlvS9TbICcasdW4JMTW2WJMC1imJX0=,tag:3u/9x4tfX8GGXSqyXAJ/Jg==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRkR6clNSZXpyd1VhN3Fn
            Mk0rNlhYNDVEVWZoUG5ITThKczJPa2lybWlrCjNPTkJyNkRiQ0NuNWlQeVYxMjRL
            cE9yRkw4SEtMeEQ5eFZkMW1KaU9xS1UKLS0tIFNDMFV2WXZQZ3gyb09ZWEI0TTZB
            YlYrSVNnem5mbEVVL01mR3ZqZHJKak0Kj4TVBdcV18R+ITtDGYTHs8iDn8UHGZS2
            1r4gzevir6ysHBqC2k1Xp77S8LNFa69g0BiJiLOv/eHsd9Yzu2PhBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T15:45:32Z"
    mac: ENC[AES256_GCM,data:uzvFDoWjo3N/ypHdzHCazNVIadbLQCgg/pa9BvBzeJLSTHdQbFo2S9s158nMAQ0w9AKclFWxttw2iLRBJ0WkYcFOj6SkExlpvnzzVKzUJ5rokOxIlcSbQe2mfrKyg3hSo7w77ZNZuybKZf8ydTOBz7bBgRXEi4RU0fUJ6XSH8Ww=,iv:S6tnOsrsJvIW3b3lmYOANCifEfw/1YnrJYgU8ji8/R4=,tag:4iSyiGg9LwONx0K8g2CKHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
