apiVersion: ENC[AES256_GCM,data:RSA=,iv:ePv8IM/Yscnf1wKzxcW02QyQCAKBx5rrpc0h/338A8s=,tag:KIpzhj5G91jRCD9EeiD+sw==,type:str]
kind: ENC[AES256_GCM,data:jt2MCX/F,iv:zWgtDX8y+vM19YQo/4zNg4Ntg7ofy4s+9XwnFIbaBgk=,tag:+sNFvINS88GNyfxuL5wA8g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Og3mBI0Xk87xe7GtkUb8nHRvLhBJrxQ=,iv:iruD6uUuSiRqeT0QbLVnq+Kjeq6oIJO0K1UkM0l8lgE=,tag:Ti5nu5LpnHLaMfMJoYtKcA==,type:str]
    namespace: ENC[AES256_GCM,data:04pd2Z7V,iv:D1Uh/+TdKUfmF6gDYIdCH1PGBQ0ZPr7XDhaJTai2UFs=,tag:97Da6bMcXi7MxAQ6fv1NAQ==,type:str]
type: ENC[AES256_GCM,data:Wq8h0Vgw,iv:5wSa73msxoD5RxlaufFjMZrnB1CriW+fZNSyiigylMU=,tag:T0sUbvkMMRFsSrkbtqeqUg==,type:str]
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:MFupcijZIxK7mcR05o0K87Bk/Nacrr62kWf2G+DTwy9R/b3lhqhOb/jFXvM=,iv:bzlbLeJ06PiALQp2vs5aeVEaU5ug5t6lSOG5Pfn7Z7c=,tag:L0o1pXzJddHbKl03tEdFoQ==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV0NSQU9PNElHZlY0MEMz
            NWtLUm9Gakg2dkZId0ZrT0kzNkpnTTIxSlNvCkxvTWRQVHB1aGkwaEJlRjYzMWZE
            ODlrcHhRdHFRNVIyMGZHL2o2Z2JhS1UKLS0tIEl6N25STGIxb2puV1NQRkhDRVZk
            THlSNVhubWlGRWFlWVRteVNoUTBFWm8KXe8Wn+0M8zWU8HYW8dYNjrg5khRg9za/
            hysT8Uba0KokcOyrcL0e7F3AIFatE+eHRhOyKlVvc4b/20uYZH1AvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T00:30:14Z"
    mac: ENC[AES256_GCM,data:QQixc7KaQ6HjmDffW+ExB/j08Q+NYtboqIAYjg69XecyWH416netTgN4q86YBLIcNlX66dadA2OsucQR51SpEPGUsbynldgpRHWOG6Sz30ZOIweOcM6sT41TJmM2kKcf/7TRRcukscP88XwH5BK6UqOnK1r4RcTyPBwbdIMV3PY=,iv:KaRCQQuhpsh6hrEtX/20lPyAAJOiCjV/y+nns4/hIYs=,tag:WY0xpJc32TcmApOTxmg4OQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
