apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - shelfmark-deployment.yaml
  - shelfmark-service.yaml
  - shelfmark-httproute.yaml
  - gluetun-secrets.sops.yaml
  - calibre-web-deployment.yaml
  - calibre-web-service.yaml
  - calibre-web-httproute.yaml
