apiVersion: v1
kind: Secret
metadata:
    name: tailscale-oauth
    namespace: tailscale
type: Opaque
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:mthYBH/i6pEY5X2t8VvSqbE=,iv:82kwyV+XtYTgfHj2IjYJUCIG85nyIlIAh9uJWc/wl2Y=,tag:dhKHv9Ek4EXzuZj1HZbcTg==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:2ktb9Tv7qdJc47Y61oP14BldFRKgfd0JEWkPA2X9BlzbWJvXIuvLHq6VbDTpOx+HS6KkLwZiNx3FR7O/Mo2Z/A==,iv:Sy9AjcF8TqYttBocKCcPGHcqamvkKeaKPe/Eno2pEU4=,tag:CEtkEZKjFYQH0XzHwl5Xuw==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRjF5V1U0REZvaFJFcDZl
            T2t0Rk1WNk1Ud21CUmltRFlZdEQyV0NKZFh3CnVQMFo0TENoVDJ2Z1IwWEowY0ZY
            NWRUaUs0VXlxRVRuWDczVGhVWm9md3MKLS0tIHJSSlY1ZnFRNFZjaWhuMEdCWVlJ
            RXpWQUdNdWM5bHlKajEzdHI5ZEozTU0KpzScZ8ckrrIb0fZq0XNjiKBO9dbyTF/k
            6vnCzwlxNhxw+zhWva+ApAUPOWqlbbUHjkBl6ZwM2UJbF5C4IeBTwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-20T21:15:44Z"
    mac: ENC[AES256_GCM,data:9ur9kh3z8d8+q0zNo/fOyYELEqJznhPtRM2ejfE8DtzhgUg4PemrzepUDhVhTGBHMjzVNePyetrd7BUJkwQgRsR4GX2F8dbzxyRkw0r6pD/XjLbsC7KyWwG6Vw66N/w1M/1Mp60rKlhZ92aHKKgizdXjzcg3sL+7oTu39a3UXG8=,iv:ocVaKHOBBbFsuA3K4cY2tzdmIPlsMzGl0fPnUYJneB8=,tag:YttQRzrZCHEaHXlrteql7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
