apiVersion: ENC[AES256_GCM,data:wjo=,iv:kMNdkA2UNbhqd8DupDYFL/JcqNjQ7PMqM5jZO463LhY=,tag:hsoeHyuqzGH+hQq6YwMceQ==,type:str]
kind: ENC[AES256_GCM,data:kPTzQG9E,iv:Jqkrv/Thf2F8ekLKUbKOZxgq9eSG2XHlya/x7oxqv10=,tag:fpcKpVV25FW6bK9GnCvP+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OFabdWN+JhhdGyuDNOC+,iv:f4Rf8LEF53e7yM/QI14lKkmmlRqqvzTwmx/+4KRaHXE=,tag:p/hFB7bM1cRV9svLBBAfkA==,type:str]
    namespace: ENC[AES256_GCM,data:S4fd13A=,iv:AcbhOz9/O1QI05t/N5cZZXE/DGqptnD013Urvx3FkGM=,tag:0Mbo+/GUEsOXqawFGqxn/Q==,type:str]
type: ENC[AES256_GCM,data:sToRZRWT,iv:nRVb2zwH3HmRUnMPvUKRQOtkC05ntrMy35Q36TdGdeg=,tag:5ysoNXZv/O/SmLIBiHBQPg==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:9F8UDEi7cEX/bu5uCnueseJFhqEXBEK7jfpky4MjohPbZb5hIR0kFmYSZLcgaUezHxlTrSs3sZd9zucZqHd7WLGnV3MMMCxC3LWYV8RwFHLATKnkovswE2NXMmMrmVKDVaxPGHMUxyX0/GZb,iv:INPON/NX0oGWICbXiFQ+P+BXRki2X0nKxujbhzMZPa4=,tag:87oBYZ4V1eYBnvRQvZRCSQ==,type:str]
#ENC[AES256_GCM,data:TZStMXJ8AaU0CPhQq5tteJlnDeJXvw==,iv:S2LA5GvIsueIWwXx/sC6rX7DGmrrfMl5p0gtukzKGEQ=,tag:lnYiwutH2lLhcpvggwAaow==,type:comment]
#ENC[AES256_GCM,data:j1CQ2yx826Wj0paAHxAUcvkXwc+BWTGjnf5IXSoMKKdwrYxtIwpynfJw8j70Dqq7NE+RRdx4Kvo4JDBwcTCpRylSow2o6+szLPGsrYEv2GjtHmW/v59ni9UrfdeyXAjtnwLWuQ==,iv:IE6XTka1Zs0LSJLuWDlIsb+cvM9dVKXzshTeVoLMN6s=,tag:yyR411jv/e0WeME4pvA4VA==,type:comment]
#ENC[AES256_GCM,data:poXp0WK+Dhnm2f4uCmLsDOriRY8pWDqKkOlyBBd7S+3A1nPLhRTtLEifO6Hnc115gL0G1MoIoCxR2ULbk2LwoAP5iSG1glQIfQlT3P3IFHsQ2PMb778b9B5E2wcIXeVbibs4YUF7bufRQG5rTGkuZ5L+FQ9VMChgt2iHmVxFwCKm09AE7LazP/c/kX8B,iv:jCR3XdBE1a2Uh1XPKGASyUxdIkUHp/lOSlctNfWILb4=,tag:nqv4Vuxy0+uhcCnRrlnOpA==,type:comment]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNjdQZlQrTGEyRXJUNGNQ
            WUJzeFdJVG9JVkpFV05iclJnbk96ZUtONkFFCml1MzhHME1ITFQ4SnJla241dmpx
            aFlDcWE2ZEVzWGJEL0hqRUNkcWQrd0UKLS0tICtNZkgxeEUrWjF4ayswdGJYQnhB
            SDFUeXdIRk5LSGxDeDVJSWtOOTFFR0kK4JB4g46xjlS05EhVTt08fXAavH2vFYaU
            BAhvxLc2jQIv9BR9rNGflR3/x5UQZ6m5Gfd5wio/5Va0nn60rzDNrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T22:09:07Z"
    mac: ENC[AES256_GCM,data:vq4WqvSnragqV5KxfGL+9lW+lzbozey4WNHxpMNsm7t9gQWIa+5/CqwYQeR4IbV/Ga0n3xZZ243SuQuKijcezEECCN20c2v+d6OWcBtSvzNCm7Xrv1MPejiIXwyka0iATTCswtQ8BTpLTE3RH9hVSdcZbzFoSw9zYIqRXRldIHg=,iv:4A0IzX6aVTSN/ejxRa0Xd4Hv7ZaD57uGKOeTcdffg4g=,tag:M75jXjFXZeNiP25/4KLJJg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
