apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-r2
    namespace: coder
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:6iAz3Ydg14grGbo/xmff79D84QXM4EICkF3MNhHcPeY=,iv:hTUcwd+fYy0sfWadTw7npJhywYnEMmH8boZOUom6oQg=,tag:DY3xZykEiCcmGtI1BlHK0w==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:XNZ8KLP8HIDsczr4IB0WPOPed/k58KtKDu9Y4FJkmWWclhAmtAGRrClsbd4zeW8hyk3xVNtVYk9qQzo6jOBCqw==,iv:MG6PEZS38V+GK5SqwYmccVs7XSxojjroitvaG26ocO4=,tag:DcP4bpInDQcnwFkE1xUp5g==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdFZsN3pIWlBaZis3c2tD
            ZzNEb01ZYmpDYm1QcXo2aWVPblV3REh2M3k0ClV6cEcrV3FUa3NIOTM1cjJja1Zr
            YVlKbzlFOVRDMUZHcG5XOWJyWUt6dTgKLS0tIDJUYlJ3cEQ0L3R5TVIrOXJYV3Nl
            aDNYT216ZXFVdlB1eFdjYzh6R1F6OW8KffZQOqgKsP6UrYyu1xC0yhEf03pN5Vl3
            qncs9zjj3BZEs/8Kg8a+WobY4Xc1uP4/S2gIlff/goRifoE8GptRAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T03:11:10Z"
    mac: ENC[AES256_GCM,data:5sBQmzAUGr2HueMyRK8f/SbJIIbRabbViWlDcAEkBzeNH9fgfxg4F2+GPLB2hr1KXNo16h+KmNKKHXT0Dt0YW2hl030UIuidggXdyPC1hn2vMluuiON1QF1vcYODlXvUsqk1AyhGwlnSvEcS8CapjB314mzyRhVa76jMQ/zjSeA=,iv:WM8RYxdUTQd0N72laHTRzzUn0uLfNvyRvrClO3SO8yk=,tag:09zcTvEX6OCGimf/IpU6/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
