apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-database
  namespace: coder
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 10Gi
    storageClass: truenas-nfs-postgres
  bootstrap:
    initdb:
      database: coder
      owner: coder
      secret:
        name: coder-database-credentials
