apiVersion: v1
kind: Secret
metadata:
    name: coder-database-credentials
    namespace: coder
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:xwdI2XE=,iv:p6YSN2B713wNpTvtYsy0gj7a8gffIMba/vQMMXd0bUk=,tag:x7eptD36jouPPBn9LpGWtw==,type:str]
    password: ENC[AES256_GCM,data:ArTaMjNd4jI1/OdIRDxx2t2uI/ECEL9w,iv:IA8lEEkLzJjef8QNOx/XIm9xamdJz90wkDz5QF1QRBU=,tag:3UkrM+Ayhg59PV41UWR8Mw==,type:str]
    database: ENC[AES256_GCM,data:i228O+o=,iv:SEipF+Xf7qHnbVbzdPbrpn0CC1lJth8LIgocZ9N4dFM=,tag:Ki/gwOxBZbfGqI13Tagf7g==,type:str]
    url: ENC[AES256_GCM,data:qZllZSu0bXgHMQ9QPKLhupmZYa9cuY28COI1mTia2sI4Hk5lkyhpZ5pWLVvhKzaUfA7koUl8PZldipeSqRLna0l+Aj5ZidJF90hO3XHPsXSTmu0e71s=,iv:fPYP10POfkbDYdpjWgF56jkwjcKguYSZAk+ozT26LTA=,tag:hnWLv+Cbn/RrxED/JIftWA==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTUVrckk3UXNIL1kxdGpk
            OGhqRVVVbEJPc1dxSUtreitQSWtZSWU1UTJBCjQvV1hVMEhsS2Ryc1JPVk5jQ0w1
            TnJRNHRYbFlCdERxMXltQmtvOER0Z0EKLS0tIFRDTmh4WGFkNmkwNkNkMEZwbGo4
            V1FVWERWLzY1OCt1Mzc1MTIrdXFSaXcKtinrnIwu6pMzbFFbOvldN7s/afVXzFzE
            wsiwPPeo0swZkf+tS4WnSxX1/5h5GTkjB/CAi7d40onSozCOa0GiNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T21:03:27Z"
    mac: ENC[AES256_GCM,data:Fhk70Xn11L4NI3dUVvuP7jhEoYWMmjfsq/9pZPWs5RhCWoOOp4YVv0nKEtKPXJ/4a0mcMqUOiMYreXLkrYrQwNlXf2eq3IgHE5Q3qqnL2HIM05FSUWttDaytFMrhsA7kpkgnXVGDgb30XPa96jTbs9EN6OKyY4l3CPTOamiNSBY=,iv:r/WWou8vSkAza8TlDQ6S0ku7W0SqDOec9/Svs3Lmu9A=,tag:kd0HOgbjfupM707/a5yMvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
