apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - httproute.yaml
  - namespace.yaml
  - paperless-ngx-secrets.sops.yaml
  - postgresql.yaml
  - pvc.yaml
  - secrets.sops.yaml
  - service.yaml
