apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-secrets
    namespace: paperless-ngx
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:cjSgHkvvbYWFNHmuZb81gU+kbJLIQj3c4GHVVcyWj7Fe4OyEUgvsylOdAodY9AgteUVdMDKWpGFQAvGoOzpFT4b/4MSLmLYsxIdy95jgMQqiPNjtRE/W/w==,iv:IlBza4uGy4meBMt9XKFAf9hFfpaDCd7zKpS+E7DgG1I=,tag:AW/DbUiykU2d6l8/WYsQLQ==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRDJ2d3N1Sk5wbGE5YTQr
            RnhpZnBwby8vTjB3dURtUTZab0l1UGNrbHk0CmUrY3RMRUpLSFhiVW1xczVDKzZ0
            NDVUOVAzeFNiOWlpUkZ6akg2U2w4TmMKLS0tIDZ2VUFNRlhRMWlkV2Z0L0hYUkJq
            RGdkOG5yK01kVEpVTkZiVDJTcEVwUmsKdOZrCEbzg8cnmA8vOgeeKgFs5XZ1JnTp
            9h1sKoBgTftMjCssfJ3BXZYWcO8k7UroXYAkWibyyDfz1/V8M0Xg3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T21:31:41Z"
    mac: ENC[AES256_GCM,data:i5X1nK/UOWcH8JcZe/7pNJ83OhSrP6SAmbNb9dp5jqJU71nuD7hRWgLY8+6ubmhOtJ0HCZvOBxIbJEXgc2Nc5K5vY2GQHxCqPbL0f46VVMYKEWAhDaIv357J/g1gXAfe+4WgRWLuF8ZDyx2uX88IsnDE8v9OC2xxUbBouCjSA1I=,iv:MUYVoYzhow+Vt4yHDAz15XIZ/+llu2cU5rKgRaf8xEw=,tag:F0lU9Do1I/EZutTe0T9jZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
