apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-ngx-database
  namespace: paperless-ngx
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 5Gi
    storageClass: truenas-nfs-postgres
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: paperless-ngx-database-credentials
