apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-r2
    namespace: paperless-ngx
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:MEdgLF8xMYUlQdZi1/O6SowjrgEbQe6vpUOlccYX9wM=,iv:wgRWL5Bh7NJYlqGycyL2dJibX9JzPjHGMbIVwriBYhw=,tag:9yv4KY0CM7zyWW0z2D359g==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:jD1Ai6fqpkHtDYvSkRgi3WUQ6ztH2dy8qJC5waWrlxTMKsP9fwVJO+N2Ejs5QTq8BpmblXbp1hQ0HnFFcuzFlA==,iv:gc7JhqLMispY/sF0Pcg0LKl9/UtLvEJN5zVlKZiDXVg=,tag:nn9iGWVmDBxE6Exduw2Jpw==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Z3NlMjhHLzdIdlRKZDAr
            UEhHWlJQdGFaNDdReGc0RHlyTlV1UUVFNkdvCnlRNnpvUGFjNmhZQlJORGhZMGN0
            VkVxRjAzTktlSHYyT2VyTDNacHdhMXMKLS0tIER4UkVKTU9pRnRrMUdJdjlKTHNZ
            d0xBTG9Kbm5FYW0zelpPb3Z2R2JQVXcKgmocaffJUZqtvJ/oDkrz7F+gKxkuv5eW
            HALSxr8Tg/59RpgWeKr8DrfGrDDrTFOA0qZBM3y3xeC3RO3mdA7VAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T03:11:10Z"
    mac: ENC[AES256_GCM,data:mXaft/KzBQD9KgtCqINky1QSPeikxdn7iwk2oO0Ir30X88W2uqawCNkDsN+D0f/nxpoJQ6lO8+qyXdh4UiSccF9N9vHyIFj4IGiUkc+qTzLVJ7YQ6WoyiMQY0ToWwYlQvRh1dAtvzFpZ6xKpWAfLspubFP7/y13px78iJaDqSgU=,iv:Wn+p/hp/OJiMBAHUOOf5c4B5FVdw1ipRsBnYrizKANk=,tag:g0Z/nLIRs21ty5F8f3WhYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
