apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-database-credentials
    namespace: paperless-ngx
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:CWeWaDvnV9P8,iv:1lFnrlwDXod9UXYYOIJblDeanGAZXKNBYVWjOqTsNK8=,tag:LrvAz/1Uk09bVYnlWLVoyQ==,type:str]
    password: ENC[AES256_GCM,data:/svLnmvxiCx9FaeQqHWDQxQW8XPEQgEhn6Jcq0SuouM2gJVjcKaG6OtOTTw=,iv:cg4agSAwBJBE+HGDZeF5O/WP+J1y/VvJ+C060JGah5g=,tag:AEx18Typ6oJR3KtdBC1KzQ==,type:str]
    database: ENC[AES256_GCM,data:gRMWlCb7ijKb,iv:xJgJkWSmWGBanJrm2rmVZqQHcNFm3fUp5ddQvWF4kVI=,tag:lg7CO9yceefWeUApKZBBrQ==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSjJyd2ZxQWVacmJDaTdX
            M2ZMZmxsV3NHemFsTzZDY1FHTFN5b3ZsbFRRCk1ja1NaYmsxS3hwemNIcEUwRSsy
            a2t1a0RlZGs4YUdNdFZhVVFnUDVvMk0KLS0tIGh2YmtzamI0dFJKS2dYZ0ZtNUJk
            bXU2dzI3ZXhPQ1BhaVBJWTR4RlpzdUEKcHL2o5XKuSAbNvEERfEHiiI1FAPkvIk+
            pP8T6ARhMoCdNsSg9lE8QQgqRzNf9u1rfydKu+K2YgX1VaRMQ+U0xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T21:31:31Z"
    mac: ENC[AES256_GCM,data:M3ChTQ2IkJhfnSfm5Czg3bxblnFbZUI3VAwd07PRyWlhCIHyzHhYHYdXMw2AkN5vgnnUj9wyQGgEid7sMIkNtZB2aE5arucDZD0gjlGUWCB4v48DmLGDQFTsZSTRA4VdBaPGUJ65AT40UqhRwyXKEQZNhm1YZtn0OlOdabZggMM=,iv:r3swvLOWznzO2N5vIStQNR0Cvy2LogmE0svurs5oQzY=,tag:eenHibvoCvn8IvB6Dyrh7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
