apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/open-webui/helm-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 10m
  chart:
    spec:
      chart: open-webui
      version: 16.1.0
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    ollama:
      enabled: false
    pipelines:
      enabled: false
    extraEnvVars:
      - name: OPENAI_API_BASE_URLS
        value: "http://llama-cpp-1-7b.llama-cpp.svc.cluster.local:8080/v1;http://llama-cpp-4b.llama-cpp.svc.cluster.local:8080/v1;http://llama-cpp-8b.llama-cpp.svc.cluster.local:8080/v1;https://api.openai.com/v1;https://generativelanguage.googleapis.com/v1beta/openai"
      - name: _OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: open-webui-api-keys
            key: openai-key
      - name: GEMINI_API_KEY
        valueFrom:
          secretKeyRef:
            name: open-webui-api-keys
            key: gemini-key
      - name: OPENAI_API_KEYS
        value: "sk-no-key-required;sk-no-key-required;sk-no-key-required;$(_OPENAI_API_KEY);$(GEMINI_API_KEY)"
      - name: DEFAULT_MODELS
        value: "Qwen3-8B-Q4_K_M"
    persistence:
      existingClaim: open-webui-data
    ingress:
      enabled: false
    service:
      type: LoadBalancer
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "chat"
        kube-vip.io/loadbalancerIPs: "${LAN_PREFIX}.27"
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
