apiVersion: ENC[AES256_GCM,data:pEQ=,iv:hELClUbqshBGGjo9hxLFBviMoZYmrvFqnb3iWSLJbFk=,tag:dr0t59Ax9TNtouS/8EOp/A==,type:str]
kind: ENC[AES256_GCM,data:pI6/iFPl,iv:smm8eSQxRO1tPpQVO3bxHXx0HQAWR86RA//sKDhTTsA=,tag:Zv9k7NBWDpqjOtNXI4drgQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:J5kqKqX+342+zwLAqjTXJdDBiQ==,iv:LVSPqzW8YUA6JALrSp8OKcnF8fCSbuPdGwDuLNTUAFQ=,tag:JHQT/0ZEcUznxlIpSN6pWQ==,type:str]
    namespace: ENC[AES256_GCM,data:ujbAV2wxSZNC7g==,iv:Ln7TdQt15zsX4+s3F9hCfgyxkndmV8d9MaifGuYIkYs=,tag:SbAEi231LW1U6/xeLBxrrg==,type:str]
stringData:
    openai-key: ENC[AES256_GCM,data:vIcWQZz0ZKRU2ngYj4O4BA8AW8zJvsiGFqC9UJ0ImL5skgmH4EB1v5OlyFXpP4Z3Zi9yvyCEzStirdkj7My6SsspfuYCVBZXFF0Oldxibnmw5O/oaK8Sm7joaq7JLlqN0X0QMCmuJRuGfn/Yw4h+epoDt7RIbtyZM56FU1xhC4URpA0u3V+AqbWqbIwX260RpvYcd6eaywqkEa3VfRYyfDGB110bdzE=,iv:s/SaKyhII0aDuoCu7Kguz+9yK1g+BuPTAVOfn2YDmBU=,tag:buI5d0YkhoffNbM45dBEtg==,type:str]
    gemini-key: ENC[AES256_GCM,data:RjVkpN1Eo03zry7urbzq3huA4r/VVzNBWKMQGWlTVUl8iMuFMis3,iv:ESfWWKaOaNmeEK1nKSCABF0diov66RSFZe+CJsQ+LRM=,tag:km4pyT7V9GqBqxS/vbW/+g==,type:str]
sops:
    age:
        - recipient: age1ssrlddcqe0jrh2g3038538wuk6uzegz49gyvak2elm7rh2ccj3pq8vnz7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMR2ErOEUvc0ZOOExPdDZB
            djJNbEMrL3hQa0x5cVdFb0F2M010M29rODB3ClpkdkpGanVxTGlDOHE2QzRVRFVs
            b28rWDBZUHBYc1N6ckNQZWZadjZhWEEKLS0tIFJtRWFWcEJNNHZVWDVNczVKM1B1
            TjBpT1FVdy9yRytIWHV3KzNtNDNYSmMK2zc71ewv4Ktk5jZdI67bwDZtU22A7s4H
            omHW8hhrxAgmyUz9eumzZ9SJeXLUMedtFng3G62ltAUmfFPNjaNSeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T01:36:18Z"
    mac: ENC[AES256_GCM,data:SNuaKDIx8RH+D/DAVW9CTzZjVSg1F/xkxpNoq0daRzPpKCqRgKicaoxbPD47XJKpXUR7ddKZxjMfge/LbxBCv6i+wRs/gG/XAPwXJlijHL3tGZ+v0Wg+AdQclnwTFg//Wv9iqnBhYjpZXdfZHqoB4UVhKMMaXrhQ86aDFcnNsPA=,iv:2cCVTjgW7U3c1HYyxc13HWt85X2lqVCFNZ9LbD2D2+E=,tag:fbteB1EQGaVzJJDM5Woduw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
